{"uid":"f35a0e063b6e1f3f","name":"test_login_form_negative","fullName":"tests.test_login_page.TestLoginForm#test_login_form_negative","historyId":"a7a6ab08b095070504a946343f4d82dc","time":{"start":1689186454983,"stop":1689186454983,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x559616fc04e3 <unknown>\n#1 0x559616cefc76 <unknown>\n#2 0x559616d18d78 <unknown>\n#3 0x559616d15029 <unknown>\n#4 0x559616d53ccc <unknown>\n#5 0x559616d5347f <unknown>\n#6 0x559616d4ade3 <unknown>\n#7 0x559616d202dd <unknown>\n#8 0x559616d2134e <unknown>\n#9 0x559616f803e4 <unknown>\n#10 0x559616f843d7 <unknown>\n#11 0x559616f8eb20 <unknown>\n#12 0x559616f85023 <unknown>\n#13 0x559616f531aa <unknown>\n#14 0x559616fa96b8 <unknown>\n#15 0x559616fa9847 <unknown>\n#16 0x559616fb9243 <unknown>\n#17 0x7f0930290b43 <unknown>","statusTrace":"E   selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n      (unknown error: DevToolsActivePort file doesn't exist)\n      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n    Stacktrace:\n    #0 0x559616fc04e3 <unknown>\n    #1 0x559616cefc76 <unknown>\n    #2 0x559616d18d78 <unknown>\n    #3 0x559616d15029 <unknown>\n    #4 0x559616d53ccc <unknown>\n    #5 0x559616d5347f <unknown>\n    #6 0x559616d4ade3 <unknown>\n    #7 0x559616d202dd <unknown>\n    #8 0x559616d2134e <unknown>\n    #9 0x559616f803e4 <unknown>\n    #10 0x559616f843d7 <unknown>\n    #11 0x559616f8eb20 <unknown>\n    #12 0x559616f85023 <unknown>\n    #13 0x559616f531aa <unknown>\n    #14 0x559616fa96b8 <unknown>\n    #15 0x559616fa9847 <unknown>\n    #16 0x559616fb9243 <unknown>\n    #17 0x7f0930290b43 <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1689186454983,"stop":1689186455693,"duration":710},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x559616fc04e3 <unknown>\n#1 0x559616cefc76 <unknown>\n#2 0x559616d18d78 <unknown>\n#3 0x559616d15029 <unknown>\n#4 0x559616d53ccc <unknown>\n#5 0x559616d5347f <unknown>\n#6 0x559616d4ade3 <unknown>\n#7 0x559616d202dd <unknown>\n#8 0x559616d2134e <unknown>\n#9 0x559616f803e4 <unknown>\n#10 0x559616f843d7 <unknown>\n#11 0x559616f8eb20 <unknown>\n#12 0x559616f85023 <unknown>\n#13 0x559616f531aa <unknown>\n#14 0x559616fa96b8 <unknown>\n#15 0x559616fa9847 <unknown>\n#16 0x559616fb9243 <unknown>\n#17 0x7f0930290b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/testing_foodgram_project_react/testing_foodgram_project_react/conftest.py\", line 26, in browser\n    browser = webdriver.Chrome(\n              ^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"feature","value":"Тесты аутентификации зарегистрированного пользователя."},{"name":"story","value":"Негативный тест: Тест аутентификации с                  использованием невалидных данных."},{"name":"tag","value":"login_test_negative(scope='function')"},{"name":"tag","value":"login_form_test(scope='class')"},{"name":"tag","value":"run(order=2)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login_page"},{"name":"subSuite","value":"TestLoginForm"},{"name":"host","value":"fv-az256-210"},{"name":"thread","value":"2518-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["login_form_test(scope='class')","run(order=2)","login_test_negative(scope='function')"]},"source":"f35a0e063b6e1f3f.json","parameterValues":[]}